name: Node

env:
  NODE_VERSION: ${{ github.event.inputs.node-version }}
  PUBLISH: ${{ github.event.inputs.publish }}

on:
  pull_request:
    branches-ignore: [ beta*, dev*, next*, nightly* ]
  push:
    branches-ignore: [ beta*, dev*, next*, nightly* ]
    tags: [ v*.*.* ]
  release:
  repository_dispatch:
    types: [ node ]
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node version'
        required: true
        default: '16.x'
      publish:
        description: 'Publish to npm'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: build
        run: npm run build
